language: cpp

before_install:
  - echo $TRAVIS_OS_NAME
  - brew update
  - brew install wxwidgets
  - brew install gettext
  - brew link --force gettext

before_script:
  - wget -qO- https://cmake.org/files/v3.1/cmake-3.1.3-Darwin-x86_64.tar.gz | tar xvz
  - ./cmake-3.1.3-Darwin-x86_64/CMake.app/Contents/bin/cmake .

script:
  - make -j4

# blacklist
branches:
  except:
    - legacy

notifications: # set notification options
  email:
    recipients:
      - developers@moneymanagerex.org
    # change is when the repo status goes from pass to fail or vice versa
    on_success: change
    on_failure: always

os: osx
compiler: clang